FROM node:14-alpine

WORKDIR /usr/src/app

COPY package*.json ./

# RUN npm ci --only=production
RUN npm install
# RUN npm ci --only=production --unsafe-perm
# RUN npm ci --ignore-scripts

# RUN npm ci --unsafe-perm
# if using ci, mind the postinstall script

COPY . .

RUN npm run build

RUN rm -r src

# COPY ./compiled .
# COPY ./public ./public

# either --env PORT=$PORT -p $PORT:$PORT
# or -p $PORT:4040
# EXPOSE 4040
CMD [ "node", "compiled/index.js" ]
