FROM node:14-alpine

WORKDIR /usr/src/app

COPY package*.json ./

# RUN npm ci --only=production
# RUN npm install
# RUN npm ci --only=production --unsafe-perm
RUN npm ci --unsafe-perm
# if using ci, mind the postinstall script
# RUN npm ci --ignore-scripts
COPY . .

RUN npm run build

COPY ./compiled .
COPY ./public ./public

# EXPOSE 4040
CMD [ "node", "compiled/index.js" ]
